language: r
cache:
  # Main R library
  packages: true
  directories:
    # PhantomJS
    - travis_phantomjs


matrix:
  allow_failures:
  - r: devel

  include:
  - r: devel
  - r: release
    # Install PhantomJS (if not cached)
    before_install:
    - "export PHANTOMJS_VERSION=2.1.1"
    - "phantomjs --version"
    - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
    - "hash -r"
    - "phantomjs --version"
    - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
    - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
    - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
    - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
    - "phantomjs --version"
    r_packages:
    - covr
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("rstudio/rmarkdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip-cleanup: true
  - r: release
    os: osx
  - r: oldrel


