language: r
cache: packages

matrix:
  allow_failures:
  - r: devel

  include:
  - r: devel
  - r: release
    r_packages:
    - covr
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip-cleanup: true
  - r: release
    os: osx
  - r: oldrel


